{% set name = "sphinx-theme-builder" %}
{% set version = "0.2.0b2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-theme-builder-{{ version }}.tar.gz
  sha256: e9cd98c2bb35bf414fe721469a043cdcc10f0808d1ffcf606acb4a6282a6f288

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python
  run:
    - python
    - nodeenv
    - packaging
    - pyproject-metadata
    - rich
    - typing_extensions  # [py<=37]
    - tomli    # [py<311]

test:
  imports:
    - sphinx_theme_builder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-theme-builder/
  description: |
    Streamline the Sphinx theme development workflow, by building upon existing standardised tools.
  summary: A tool for authoring Sphinx themes with a simple (opinionated) workflow.
  dev_url: https://github.com/pradyunsg/sphinx-theme-builder
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://sphinx-theme-builder.readthedocs.io

extra:
  recipe-maintainers:
    - gforsyth
