{% set name = "sphinx-theme-builder" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 40b4bc2275b04d76781722c2e597770159e512f166986e1ceca1580a693f27bb

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python
  run:
    - python
    - diagnostic >=2.0.0
    - nodeenv
    - packaging
    - pyproject-metadata >=0.10.0
    - rich
    - setuptools
    - tomli    # [py<311]

test:
  imports:
    - sphinx_theme_builder
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/sphinx-theme-builder/
  dev_url: https://github.com/pradyunsg/sphinx-theme-builder
  doc_url: https://sphinx-theme-builder.readthedocs.io
  summary: A tool for authoring Sphinx themes with a simple (opinionated) workflow.
  description: |
    Streamline the Sphinx theme development workflow, by building upon existing standardised tools.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
